## NUMPY:
- Numpy stands for numrical python
- Numpy is used for numerical computation.Directly you may not use it.But Libraries like pandas etc,use numpy for numerical computation.
- Numpy uses ndarrays for numerical computation.
- It provides powerful tools for working with arrays and matrices, along with a wide array of mathematical functions.
- Numpy is the base foundation of all the libraries


## Why We use Numpy?

- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions (statisitcal functions) that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

- you can do much more arithmetic operations with ndarrays that you cannot do with lists.Also operations with ndarrays will be much more faster than lists.

## Why is NumPy Faster Than Lists?
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

- This behavior is called locality of reference in computer science.

- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

- Lists is like storage data structure,these are not meant to perform operations

In [1]:
#first we have to import library to use it
import numpy as np

In [11]:
import time

# Create Python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# Create NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

# Time list addition (element-wise using loop)
start = time.time()
list_result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("List addition time:", end - start)

# Time NumPy array addition (vectorized)
start = time.time()
array_result = arr1 + arr2
end = time.time()
print("NumPy addition time:", end - start)


List addition time: 0.1012420654296875
NumPy addition time: 0.0030035972595214844


<p align="center"> <img src="numvslist.png" alt="My Image" width="300" height="200"> </p>


In [7]:
# NumPy arrays use less memory compared to Python lists for storing numerical data:
import sys
import numpy as np

# Create a list of 1000 numbers (from 0 to 999)
py_list = list(range(1000))

# Create a NumPy array of 1000 numbers (from /0 to 999)
np_array = np.arange(1000)

# Find memory used by Python list:
# sys.getsizeof(py_list) gives memory of the list object itself
# sum(sys.getsizeof(item) for item in py_list) adds memory of each number inside the list
list_memory = sys.getsizeof(py_list) + sum(sys.getsizeof(item) for item in py_list) #total memory = memory of the list + memory of each element inside it



# Find memory used by NumPy array (in bytes)
# np_array.nbytes gives total memory used by all numbers in the array
array_memory = np_array.nbytes

# Print both memory sizes
print("Memory used by Python list:", list_memory, "bytes")
print("Memory used by NumPy arra:", array_memory, "bytes")


Memory used by Python list: 36056 bytes
Memory used by NumPy arra: 4000 bytes


In [9]:
import sys
import numpy as np

# Create Python list of 1000 float numbers
py_list = [float(i) for i in range(1000)]

# Create NumPy array of 1000 float numbers
np_array = np.arange(1000, dtype='float64')

# Calculate memory used by Python list
list_memory = sys.getsizeof(py_list) + sum(sys.getsizeof(item) for item in py_list)

# Calculate memory used by NumPy array
array_memory = np_array.nbytes

# Print results
print("Memory used by Python float list:", list_memory, "bytes")
print("Memory used by NumPy float array:", array_memory, "bytes")


Memory used by Python float list: 32856 bytes
Memory used by NumPy float array: 8000 bytes


### CREATING NDARRAYS
- NumPy is used to work with arrays. The array object in NumPy is called ndarray.

- We can create a NumPy ndarray object by using the array() function.

In [61]:
l1=[1,2,3,4,5,6]
a1=np.array(l1)  #as there is no direct function availabe,that is why we use it with numpy module
a1

array([1, 2, 3, 4, 5, 6])

In [62]:
type(a1)

numpy.ndarray

In [16]:
t1=(1,2,3,4,5,6)
a1=np.array(t1)
a1

array([1, 2, 3, 4, 5, 6])

In [64]:
type(a1)

numpy.ndarray

In [65]:
#using range function:
a1=np.array(range(1,10))
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# ATTRIBUTES IN NDARRAYS
a1.shape    # it tells us about shape of array: The shape of an array is the number of elements in each dimension.

(9,)

In [67]:
a1.dtype   #int32: Means a 32-bit integer. It can store whole numbers from −2,147,483,648 to 2,147,483,647.


dtype('int32')

In [91]:
a1.ndim #number of dimensions:A dimension in arrays is one level of array depth (nested arrays).

1

In [69]:
l1=[1,2,3,4]
l2=[1,2,3,4]
a2=np.array([l1,l2])  #as there is no direct function availabe,that is why we use it with numpy module
a2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [70]:
a2.shape

(2, 4)

In [71]:
a2.ndim

2

In [85]:
a3 = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [87]:
a3.shape

(2, 2, 2)

In [89]:
a3.ndim

3

In [12]:
import numpy as np
n=['1','2',2]
a=np.array(n)
a

array(['1', '2', '2'], dtype='<U11')

### DIMENSIONS IN ARRAY: The dimension of a NumPy array means how many levels of data it has — like rows, columns, or more.

- 0-D ARRAY: 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
- 1-D ARRAY:  An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
- 2-D ARRAY : An array that has 1-D arrays as its elements is called a 2-D array.
- 3-D ARRAY : An array that has 2-D arrays (matrices) as its elements is called 3-D array.






In [104]:
# EXAMPLE OF 0-D ARRAY
arr0 = np.array(42)

print(arr0)

42


In [106]:
# EXAMPLE OF 1-D ARRAY
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [108]:
# EXAMPLE OF 2-D ARRAY
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
# EXAMPLE OF 3-D ARRAY
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
arr3.shape

(2, 2, 3)

In [131]:
a1 = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [133]:
a1.ndim

3

In [135]:
a1.shape

(2, 2, 2)

In [137]:
a3 = np.array([[[1,2],[3,4]], [[5,6], [7,8]],[[1,2],[3,4]], [[5,6], [7,8]]])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [139]:
a3.ndim

3

In [141]:
a3.shape

(4, 2, 2)

In [145]:
#parameter dtype in ndarray
l1=[1,2,3,4,5,6]
a1=np.array(l1,dtype=float)
a1

array([1., 2., 3., 4., 5., 6.])

In [147]:
a1.dtype

dtype('float64')

In [155]:
l1=[1.2,3.3,2.4,3,4,5,6.6]
a1=np.array(l1,dtype=int)
a1

array([1, 3, 2, 3, 4, 5, 6])

### Typecasting ndarrays
- Typecasting in NumPy (for ndarrays) means changing the data type of the elements in an array. It's like converting numbers into decimals, integers into strings, or any other supported type.

In [158]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [160]:
a = a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [162]:
a = a.astype(int)
a

array([1, 2, 3, 4, 5])

In [19]:
a1 = np.array([10, 20, 30])
str_arr = a1.astype(str)  # Now holds strings
str_arr

array(['10', '20', '30'], dtype='<U11')

### Creating ndarrays by specifying a range

In [165]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
a1 = np.arange(0,21,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [169]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
a1 = np.arange(10, dtype = float)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
a1 = np.arange(10, dtype = int)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating ndarrays of ones: 
- Creating a NumPy ndarray filled with ones
- By default, np.ones() creates float64 values

In [9]:
# 1D Array of Ones
arr_1d = np.ones(5,dtype=int) 
print(arr_1d)

[1 1 1 1 1]


In [48]:
#2D Array (Matrix) of Ones
arr_2d = np.ones((3, 4),dtype=int)  # 3 rows, 4 columns
print(arr_2d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [52]:
# 3D Array (Tensor) of Ones
arr_3d = np.ones((2, 3, 4),dtype=int)  # 2 layers, each 3x4
print(arr_3d)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [60]:
arr_bool = np.ones(3, dtype=bool)
print(arr_bool)

[ True  True  True]


#### Why Use np.ones()?
- Initialize weights in machine learning.



In [64]:
#Examples:
# create an ndarray of (5,5)
arr5 = np.ones((5,5))
print(arr5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [68]:
arr = np.ones((3,2,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Creating ndarrays of zeros:
- Just like np.ones(), NumPy provides np.zeros() to create arrays filled with 0s

In [76]:
# 1D array of zeros
arr_1d = np.zeros(5)  # [0., 0., 0., 0., 0.]
print(arr_1d)


[0. 0. 0. 0. 0.]


In [84]:
#2D Array of zeros
arr_2d = np.zeros((5,5))  # [0., 0., 0., 0., 0.]
print(arr_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [88]:
#3D Array of zeros
arr_2d = np.zeros((3,3,2))  # 3 layers, each 3x2
print(arr_2d)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


### Creating ndarrays of specified values
- NumPy provides multiple ways to create arrays with custom values (not just 0 or 1)

#### Using np.full() (Fill with a Single Value)
- If you want an array filled with the same value (like 5, -1, etc.):
- Syntax: np.full(shape, fill_value)


In [106]:
# 1D array of 5s
arr_1d = np.full(3, 5)  # [5, 5, 5]

# 2D array of -1s
arr_2d = np.full((2, 3), -1)  # [[-1, -1, -1], [-1, -1, -1]]
print("Array of value 5 : ",arr_1d)
print()
print("Array of value -1: \n",arr_2d)

Array of value 5 :  [5 5 5]

Array of value -1: 
 [[-1 -1 -1]
 [-1 -1 -1]]


#### Using np.fill() (Modify Existing Array)
- If you already have an array and want to fill it with a value:



In [127]:
arr = np.empty(3)  # Uninitialized array
arr.fill(7)        # Now: [7., 7., 7.]
print(arr)

[7. 7. 7.]


### Creating an identity matrix
- An identity matrix is a special type of square matrix in which all the elements on the main diagonal are 1, and all other elements are 0.
- Identity matrix is always square (same number of rows and columns).

- Useful in linear algebra, especially for matrix multiplication (like multiplying with inverse or itself).
- NumPy provides two main functions to create identity matrices:
  *  Using np.eye(N)
  - Using np.identity(N)
- For testing and algorithm validation




In [21]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
identity = np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
identity = np.identity(5,dtype= int)
print(identity)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


###### Some identity and inverse operations on numbers
- Identity keeps value same; inverse undoes the operation to return to the identity.
<table>
  <thead>
    <tr>
      <th>Operation</th>
      <th>Identity</th>
      <th>Inverse</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>+</td>
      <td>0</td>
      <td>−x</td>
    </tr>
    <tr>
      <td>−</td>
      <td>0</td>
      <td>x</td>
    </tr>
    <tr>
      <td>*</td>
      <td>1</td>
      <td>1/x</td>
    </tr>
    <tr>
      <td>/</td>
      <td>1</td>
      <td>x</td>
    </tr>
  </tbody>
</table>


When we multiply any matrix with identity matrix, we get same matrix

###  OPERATIONS ON NDARRAYS

In [38]:
# comparison with lists: lists are not meant for computational purposes, while ndarrays are strictly meant for computational purpose

##### Arithmetic Operations on ndarrays in NumPy
- Arithmetic operations in NumPy are performed element-wise between arrays of the same shape (or broadcastable shapes). NumPy overloads Python operators (+, -, *, /, etc.) so that they work directly on arrays.

In [41]:
# list
l = [1,2,3,4,5,6]
l + 2   # in lists addition, was not possible

TypeError: can only concatenate list (not "int") to list

In [47]:
arr= np.array([1,2,3,4,5,6,7,8])
arr2 = arr + 3
print("New Array : ",arr2)

New Array :  [ 4  5  6  7  8  9 10 11]


In [55]:
arr1= np.array([1,2,3,4,5,6,7,8])
arr2 =np.array([10,20,30,40,50,60,70,80])
arr3 = arr1 + arr2
print("New Array : ",arr3)

New Array :  [11 22 33 44 55 66 77 88]


In [59]:
#INCASE OF LISTS:
l=[1,2,3,4,5]
l2=[10,20,30,40,50]  
print(l+l2)  #The + operator concatenates the two lists,

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


In [75]:
# for list:
l = [1, 2, 3, 4, 5]
l2 = [10, 20, 30, 40, 50]

result = []
for i in range(len(l)):  # Assumes both lists have the same length
    result.append(l[i] + l2[i])

print(result)  # Output: [11, 22, 33, 44, 55]

[11, 22, 33, 44, 55]


In [81]:
#Subtraction
arr= np.array([1,2,3,4,5,6,7,8])
arr2 = arr - 3
print("New Array : ",arr2)

New Array :  [-2 -1  0  1  2  3  4  5]


In [83]:
arr1= np.array([1,2,3,4,5,6,7,8])
arr2 =np.array([10,20,30,40,50,60,70,80])
arr3 =  arr2 - arr1
print("New Array : ",arr3)

New Array :  [ 9 18 27 36 45 54 63 72]


In [85]:
#Division
arr= np.array([1,2,3,4,5,6,7,8])
arr2 = arr / 2
print("New Array : ",arr2)


New Array :  [0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [87]:
arr1= np.array([1,2,3,4,5,6,7,8])
arr2 =np.array([10,20,30,40,50,60,70,80])
arr3 =  arr2 / arr1
print("New Array : ",arr3)

New Array :  [10. 10. 10. 10. 10. 10. 10. 10.]


In [89]:
# Power  or exponential
arr= np.array([1,2,3,4,5,6,7,8])
arr2 = arr ** 2
print("New Array : ",arr2)

New Array :  [ 1  4  9 16 25 36 49 64]


In [93]:
arr1= np.array([1,2,3,4,5,6,7,8])
arr2 =np.array([1,2,3,4,5,6,7,8])
arr3 =  arr2 ** arr1
print("New Array : ",arr3)

New Array :  [       1        4       27      256     3125    46656   823543 16777216]


In [99]:
# Examples
a = np.array([2, 4, 6])

print(a + 5)   # [7 9 11]
print(a * 3)   # [6 12 18]
print(a / 2)   # [1. 2. 3.]
print(a // 2)  # [1 2 3]
print(a ** 2)  # [4 16 36]

[ 7  9 11]
[ 6 12 18]
[1. 2. 3.]
[1 2 3]
[ 4 16 36]


In [105]:
#example
arr = np.empty(3)  # Uninitialized array
# Now: [7., 7., 7.]
print(arr *4)

[ 64. 128. 192.]


In [107]:
#operation on different shapes
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [109]:
# Common Errors
# ❌ Shape mismatch:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print(a + b)  # This will raise ValueError due to incompatible shapes

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [7]:
arr1= np.array([1,2,3,4,5,6,7,8])
arr2 =np.array([1,2,3,4,5,6,7,8])
arr3 =  arr1 ** arr2 
print("New Array : ",arr3)

New Array :  [       1        4       27      256     3125    46656   823543 16777216]


##### COMPARISON OPERATIONS:
- NumPy provides a comprehensive set of comparison operations for ndarrays that allow you to compare arrays element-wise. These operations return boolean arrays where each element indicates the result of the comparison.

In [13]:

arr1= np.array([1,2,3,4,5,6,7,8])
arr2 =np.array([11,22,23,4,25,36,47,78])
arr3 =  arr1 < arr2 
print("New Array : ",arr3)

New Array :  [ True  True  True False  True  True  True  True]


In [17]:
#INCOMPARISON TO LIST: comparison for just one or first element only
l1=[11,2,3,4,5]
l2=[10,20,30,40,50]
l1<l2

False

In [30]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
# Element-wise comparisons
print(a == b)  # [False  True False]
print(a != b)  # [ True False  True]
print(a < b)   # [ True False False]
print(a <= b)  # [ True  True False]
print(a > b)   # [False False  True]
print(a >= b)  # [False  True  True]

[False  True False]
[ True False  True]
[ True False False]
[ True  True False]
[False False  True]
[False  True  True]


In [42]:
a = np.array([11, 2, 23]) 
a < 3

array([False,  True, False])

In [44]:
# incomparison to lists, It is not possible
a = [11, 2, 23]
a < 3

TypeError: '<' not supported between instances of 'list' and 'int'

In [54]:
#here dimensions are different but number of elements are same
a = np.array([1, 2, 3])
b = np.array([[2, 2, 2],[2,3,4]])
# Element-wise comparisons
print(a< b) 

[[ True False False]
 [ True  True  True]]


In [62]:
#here dimensions are different but number of elements are same
a = np.array([1, 2, 3,4,5])
b = np.array([[2, 2, 2],[2,3,4]])
print(a< b)  

ValueError: operands could not be broadcast together with shapes (5,) (2,3) 

- Function equivalents of the comparison operators:


In [67]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(np.greater(a, b))      # a > b
print(np.greater_equal(a, b)) # a >= b
print(np.less(a, b))         # a < b
print(np.less_equal(a, b))   # a <= b
print(np.equal(a, b))        # a == b
print(np.not_equal(a, b))    # a != b

[False False  True]
[False  True  True]
[ True False False]
[ True  True False]
[False  True False]
[ True False  True]


#### INDEXING AND SLICING
- NumPy provides powerful indexing and slicing operations that allow you to access and modify array elements efficiently.

In [85]:
a = np.array([1, 2, 3])
print("Element at : ",a[1])
print("Element at : ",a[0])
print("Element at : ",a[2])



Element at :  2
Element at :  1
Element at :  3


##### Accessing Single Elements
- Use [row, column] where:

- Rows are numbered from top (0) to bottom

- Columns are numbered from left (0) to right

In [120]:
#2D Arrays (Like a Grid)
#For tables/matrices, use [row, column]
# 2D array (like a table)
l=[[1, 2, 3],[4, 5, 6],[7, 8, 9]]
table = np.array(l)
# Get first row, first column
print(table[0, 0])  # → 1

print(table[1, 2])  # → 6
print(table[2, 2])  #9
print(table[1,1])  #5

1
6
9
5


In [122]:
# Get entire first row (all columns from row 0)
l=[[1, 2, 3],[4, 5, 6],[7, 8, 9]]
grid = np.array(l)
print(grid[0, :])  # → [1, 2, 3]



[1 2 3]


In [124]:
# Get entire second column (all rows from column 1)
l=[[1, 2, 3],[4, 5, 6],[7, 8, 9]]
grid = np.array(l)
print(grid[:, 1])  # → [2, 5, 8]

[2 5 8]


In [146]:

grid = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Diagonal positions:",grid[[0,1,2], [0,1,2]]) 

Diagonal positions: [1 5 9]


#### RESHAPE OF ARRAY
- Reshaping an array means changing its shape (i.e., dimensions) without changing its data.
- syntax : array.reshape(new_shape)
- new_shape must contain the same total number of elements as the original.
- reshape() returns a new array (doesn’t modify original).








In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print("Previous shape :",arr.shape)
print("Previous Dimension :",arr.ndim)
print()
print(reshaped)
print("New shape :",reshaped.shape)
print("New Dimension :",reshaped.ndim)


Previous shape : (6,)
Previous Dimension : 1

[[1 2 3]
 [4 5 6]]
New shape : (2, 3)
New Dimension : 2


In [23]:
arr = np.arange(12)
print("previous array : ",arr)
print()
print("New array : \n",arr.reshape(3, 4))



previous array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

New array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
a.shape

(16,)

In [44]:
a2= a.reshape(16,1)
a2   # here now it means 16 rows and one column

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [29]:
arr = np.array([1, 2, 3, 4])
# arr.reshape(3, 2) ❌ Error: 4 elements cannot reshape into (3, 2)
print(arr.reshape(3, 2))

ValueError: cannot reshape array of size 4 into shape (3,2)

In [31]:
#  Using -1 (Auto Calculate Dimension)
# You can use -1 to let NumPy automatically calculate that dimension.
arr = np.arange(8)
print(arr.reshape(2, -1))  # NumPy calculates the columns

[[0 1 2 3]
 [4 5 6 7]]


In [54]:
# you have an ndarray of 36 elements,find out the number of all possible 2d reshape operations
a = np.arange(36)
a.reshape((1,36))
a.reshape((2,18))
a.reshape((3,12))
a.reshape((4,9))
a.reshape((6,6))
a.reshape((9,4))
a.reshape((12,3))
a.reshape((18,2))
a.reshape((36,1))
print('Total possible 2d shapes : ', 9)

Total possible 2d shapes :  9


In [70]:
# program to  check how many 2d possible shapes are possible
def possible_2d_reshapes(arr):
    size = arr.size          # Get total number of elements in the array
    reshapes = []            # Create an empty list to store valid shapes
    
    # Loop through all numbers from 1 to size
    for i in range(1, size + 1):
        if size % i == 0:    # Check if 'i' is a factor of size (i.e., divides evenly)
            # If yes, then (i, size//i) is a valid shape
            reshapes.append((i, size // i))
    
    return reshapes          # Return the list of valid 2D reshapes
arr=np.arange(20)
possible_2d_reshapes(arr)

[(1, 20), (2, 10), (4, 5), (5, 4), (10, 2), (20, 1)]

- What does (i, size // i) mean?
- It means:Reshape the array into i rows, and size // i columns
- Because:
  - rows × columns = total elements
- - i × (size // i) = size ✅

#### TRANSPOSE OF AN NDARRAY
- In NumPy, transpose refers to flipping the dimensions of an array. That means rows become columns and columns become rows.
- Syntax - np.transpose(array, axes=None) OR array.T

In [80]:
arr = np.array([[1, 2], [3, 4]])
print(arr.T)  

[[1 3]
 [2 4]]


In [84]:
arr = np.array([[1, 2], [3, 4]])
print(np.transpose(arr))

[[1 3]
 [2 4]]


In [86]:
# 1D ARRAY EXAMPLE
arr = np.array([1, 2, 3])
print(arr.T)          # No change
print(np.transpose(arr))  # No change

[1 2 3]
[1 2 3]


In [88]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)        # (2, 3)
print(a.T.shape)      # (3, 2)

(2, 3)
(3, 2)


In [92]:
# 3D Array Transpose
arr = np.arange(24).reshape(2, 3, 4)
transposed = np.transpose(arr, (1, 0, 2))
print(transposed.shape)  # (3, 2, 4)
# Means :Swap axis 0 and axis 1
#         Keep axis 2 as it is



(3, 2, 4)


## FUNCTIONS IN ARRAYS

In [5]:
a = np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [7]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.square(a)  #square 
arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr = np.sqrt(a)   #Square root
arr 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
arr = np.cbrt(a)   #cube root
arr 

array([0.        , 1.        , 1.25992105, 1.44224957, 1.58740105,
       1.70997595, 1.81712059, 1.91293118, 2.        , 2.08008382])

In [21]:
a=np.array([-1,-2,-3,-4,4,5,6,-7,-8])
arr=np.abs(a)   #absolute value
arr

array([1, 2, 3, 4, 4, 5, 6, 7, 8])

In [53]:
arr1 =np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.add(arr1,arr2)  # this functions adds two arrays
arr3



array([5, 7, 9])

In [55]:
arr1 = np.array([1,22,3])
arr2 = np.array([4,5,6])
arr3 = np.subtract(arr1,arr2)  # this functions subtracts two arrays
arr3


array([-3, 17, -3])

In [57]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.multiply(arr1,arr2)  # this functions multiplies two arrays
arr3


array([ 4, 10, 18])

In [59]:
arr1 = np.array([2,3,6,77,88,99,100])
arr2 = np.array([14,15,26,34,43,46,77])
arr3 = np.maximum(arr1,arr2)  # this functions gives maximum of numbers between two array elements
arr3


array([ 14,  15,  26,  77,  88,  99, 100])

In [61]:
arr1 = np.array([2,3,6,77,88,99,100])
arr2 = np.array([14,15,26,34,43,46,77])
arr3 = np.minimum(arr1,arr2)  # this functions gives minimum of numbers between two array elements
arr3

array([ 2,  3,  6, 34, 43, 46, 77])

In [63]:
arr1 = np.array([2,3,6,77,88,99,100])
arr2 = np.array([14,15,26,34,43,46,77])
arr3 = np.greater(arr1,arr2)  # this functions compares numbers between two array elements
arr3

array([False, False, False,  True,  True,  True,  True])

In [51]:
arr1 =np.array([2,3,6,77,88,99,100])
arr2 = np.array([14,15,26,34,43,46,77])
arr3 = np.less(arr1,arr2)  # this functions compares numbers between two array elements
arr3

array([ True,  True,  True, False, False, False, False])

In [73]:
#Mean
arr1 =np.array([2,3,6,77,88,99,100])
print("Mean of an elements : ",np.mean(arr1))


Mean of an elements :  53.57142857142857


In [79]:
arr1 =np.array([[2,3,6,77,88,99,100],[2,13,26,717,828,199,100]])
print("Mean of an elements : ",np.mean(arr1))   #here mean will be of all elements 

Mean of an elements :  161.42857142857142


In [101]:
arr1 =np.array([2,3,6,77,88,99,100])
print("Median of an elements : ",np.median(arr1))    #The median is the middle value in a sorted list of numbers.


Median of an elements :  77.0


In [103]:
arr1 =np.array([2,3,6,77,88,87,99,100])
print("Median of an elements : ",np.median(arr1))     #If the list has an even number of elements, the median is the average of the two middle values



Median of an elements :  82.0


In [99]:
arr1 =np.array([2,3,6,77,88,99,100])
print("Variance of an elements : ",np.var(arr1))   

Variance of an elements :  1919.1020408163265


In [97]:
arr1 =np.array([2,3,6,77,88,99,100])
print("Standard Deviation of an elements : ",np.std(arr1))   

Standard Deviation of an elements :  43.80755689166341


In [15]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [17]:
a.shape

(8, 8)

In [19]:
a.mean()

31.5

In [23]:
a.mean(axis = 0)  #Axis 0 means columns

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [27]:
a.mean(axis = 1) #Axis 1 means Rows

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

##### SOME MORE FUNCTIONS:`

In [32]:
x = np.array([10,30,80,20,40])
x

array([10, 30, 80, 20, 40])

In [42]:
np.argmax(x) #gives index of highest elements

2

In [40]:
np.argmin(x) #gives index of lowest elements

0

In [44]:
a1 = np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1


array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [46]:
np.argmax(a1)   #gives index of highest elements

9

In [9]:
np.argmax(a1, axis = 0) #gives index of highest elements along columns

array([1, 2, 1, 1], dtype=int64)

In [11]:
np.argmin(a1, axis = 0) #gives index of lowest elements along columns

array([0, 0, 2, 2], dtype=int64)

In [13]:
np.argmin(a1, axis = 1) #gives index of highest elements along rows

array([1, 0, 2], dtype=int64)

In [52]:
print(a1)

[[ 2  1  5  4]
 [ 3  5  6  7]
 [ 3 10  2  3]]


In [54]:
a1.ravel()   #it converts array into single dimensional array or singular array


array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [56]:
a2 = a1.reshape(1,3,4)
a2

array([[[ 2,  1,  5,  4],
        [ 3,  5,  6,  7],
        [ 3, 10,  2,  3]]])

In [58]:
a2.shape

(1, 3, 4)

In [62]:
a2 = a2.squeeze()  #squeeze() function is used to remove dimensions of size 1 from an array's shape.
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [76]:
a2.shape  #first shape was 1,3,4.. nownp.concatenate((a1,a2)) shape is 3,4..we removed unnecessary 1 or squeezes

(5,)

#### CONCATENATION

In [72]:
a1 = np.arange(5)
a2 = np.arange(5,10)

In [78]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a1 = a1.reshape(1,5)
a2 = a2.reshape(1,5)
print(a1)
print(a2)

[[0 1 2 3 4]]
[[5 6 7 8 9]]


In [82]:
np.concatenate((a1,a2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
np.concatenate((a1,a2), axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
np.concatenate((a1,a2), axis = 1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [88]:
a1 = a
a2 = a.T
print(a1)
print()
print(a2)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]

[[ 0  8 16 24 32 40 48 56]
 [ 1  9 17 25 33 41 49 57]
 [ 2 10 18 26 34 42 50 58]
 [ 3 11 19 27 35 43 51 59]
 [ 4 12 20 28 36 44 52 60]
 [ 5 13 21 29 37 45 53 61]
 [ 6 14 22 30 38 46 54 62]
 [ 7 15 23 31 39 47 55 63]]


In [90]:
np.concatenate((a1,a2), axis = 1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  0,  8, 16, 24, 32, 40, 48, 56],
       [ 8,  9, 10, 11, 12, 13, 14, 15,  1,  9, 17, 25, 33, 41, 49, 57],
       [16, 17, 18, 19, 20, 21, 22, 23,  2, 10, 18, 26, 34, 42, 50, 58],
       [24, 25, 26, 27, 28, 29, 30, 31,  3, 11, 19, 27, 35, 43, 51, 59],
       [32, 33, 34, 35, 36, 37, 38, 39,  4, 12, 20, 28, 36, 44, 52, 60],
       [40, 41, 42, 43, 44, 45, 46, 47,  5, 13, 21, 29, 37, 45, 53, 61],
       [48, 49, 50, 51, 52, 53, 54, 55,  6, 14, 22, 30, 38, 46, 54, 62],
       [56, 57, 58, 59, 60, 61, 62, 63,  7, 15, 23, 31, 39, 47, 55, 63]])

In [92]:
np.concatenate((a1,a2), axis = 0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56],
       [ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63]])

### RANDOM NUMBERS IN NUMPY
- NumPy provides a powerful module called numpy.random to generate random numbers, perform random sampling, and work with probability distributions.
- For simulation (e.g., Monte Carlo)

- For machine learning (train/test splitting, weights initialization)

- For games, encryption, and testing

In [97]:
np.random.randint(1,10)

5

In [99]:
np.random.randint(50)

33

In [101]:
np.random.randint(1,100,10)

array([45, 14, 36, 28, 45, 78, 59, 13, 54,  8])

In [105]:
np.random.randint(11,100,(10,10))  #it generated 10 by 10 matrix .. whose values will be between 11 and 100

array([[93, 59, 45, 73, 57, 24, 44, 15, 37, 40],
       [31, 56, 39, 44, 96, 83, 14, 13, 67, 73],
       [14, 16, 46, 97, 83, 11, 36, 18, 21, 98],
       [97, 64, 25, 33, 98, 89, 21, 85, 55, 60],
       [56, 79, 35, 68, 28, 42, 98, 84, 46, 88],
       [44, 83, 94, 45, 64, 28, 36, 75, 65, 69],
       [35, 21, 94, 14, 24, 85, 59, 73, 85, 81],
       [89, 76, 83, 21, 40, 51, 24, 53, 69, 37],
       [58, 30, 24, 20, 28, 54, 94, 91, 21, 89],
       [78, 69, 16, 97, 63, 78, 48, 93, 32, 23]])

In [112]:
np.random.rand(10)  #generates an array of 10 random floating-point numbers between 0.0 and 1.0

array([0.49071878, 0.00770451, 0.09094797, 0.01696564, 0.92379045,
       0.83431154, 0.37124918, 0.14331344, 0.27788342, 0.36929481])

In [124]:
np.random.randn(10) #generates an array of 10 random numbers sampled from the standard normal distribution (also called Gaussian distribution).

array([-1.89799083,  0.06744757,  0.72458562,  0.39164635,  1.34878072,
        1.0580529 ,  0.24314872, -1.92283046,  1.0951712 , -1.50227921])

In [126]:
np.random.randn(3,4)  #generates a 2D array of shape (3 rows, 4 columns).Each element is a random float sampled from the standard normal distribution.



array([[ 0.16983044, -1.30620288,  0.12152685, -0.81330684],
       [-0.95040428,  0.84123168, -0.2239404 , -2.06105555],
       [-0.2597216 , -0.86980624, -0.83092624,  1.33769779]])

## Conditional Indexing
- Conditional Indexing in NumPy allows you to select elements from an array based on a condition. Instead of loops, you write a condition directly on the array.

- It's a very fast, clean, and Pythonic way to filter, modify, or analyze arrays.

In [131]:
a = np.random.randint(11,100,(8,8))
a

array([[63, 98, 63, 88, 97, 73, 17, 97],
       [65, 22, 22, 45, 67, 97, 97, 75],
       [69, 14, 67, 95, 38, 67, 40, 82],
       [54, 20, 65, 71, 68, 86, 50, 37],
       [97, 75, 96, 12, 89, 58, 55, 13],
       [72, 63, 35, 95, 88, 55, 32, 86],
       [72, 21, 50, 15, 43, 78, 37, 96],
       [66, 34, 78, 21, 40, 63, 72, 91]])

In [133]:
a > 50

array([[ True,  True,  True,  True,  True,  True, False,  True],
       [ True, False, False, False,  True,  True,  True,  True],
       [ True, False,  True,  True, False,  True, False,  True],
       [ True, False,  True,  True,  True,  True, False, False],
       [ True,  True,  True, False,  True,  True,  True, False],
       [ True,  True, False,  True,  True,  True, False,  True],
       [ True, False, False, False, False,  True, False,  True],
       [ True, False,  True, False, False,  True,  True,  True]])

In [137]:
a[a > 50] #this is called boolean masking

array([63, 98, 63, 88, 97, 73, 97, 65, 67, 97, 97, 75, 69, 67, 95, 67, 82,
       54, 65, 71, 68, 86, 97, 75, 96, 89, 58, 55, 72, 63, 95, 88, 55, 86,
       72, 78, 96, 66, 78, 63, 72, 91])

Wherever the mask is True, the corresponding value from the original array is selected.

Wherever it is False, it is ignored.



In [140]:
a[a <= 40]

array([17, 22, 22, 14, 38, 40, 20, 37, 12, 13, 35, 32, 21, 15, 37, 34, 21,
       40])

In [142]:
a[a == 16]

array([], dtype=int32)

In [146]:
b = a[a < 40]  # first this thing will be checked
print(b)
b[b > 20] 

[17 22 22 14 38 20 37 12 13 35 32 21 15 37 34 21]


array([22, 22, 38, 37, 35, 32, 21, 37, 34, 21])

### Slicing in Multidimensional Arrays
- Slicing is used to extract a portion of an array by specifying start, stop, and step indices.
For multidimensional arrays, slicing is done separately for each axis (dimension).

In [149]:
a = np.random.randint(10,100,(10,10))
a

array([[14, 65, 50, 94, 56, 68, 71, 64, 47, 22],
       [60, 71, 18, 43, 78, 11, 40, 42, 62, 77],
       [61, 68, 25, 58, 49, 23, 86, 77, 49, 60],
       [26, 46, 51, 96, 66, 79, 17, 12, 33, 75],
       [92, 23, 57, 69, 67, 75, 72, 59, 73, 46],
       [54, 93, 73, 57, 52, 82, 96, 48, 68, 55],
       [79, 44, 82, 46, 10, 35, 98, 22, 77, 11],
       [62, 70, 58, 94, 52, 41, 56, 10, 32, 79],
       [98, 73, 96, 42, 62, 29, 68, 13, 32, 39],
       [76, 42, 50, 20, 74, 59, 76, 45, 99, 14]])

In [153]:
a[0]

array([14, 65, 50, 94, 56, 68, 71, 64, 47, 22])

In [155]:
a[1]

array([60, 71, 18, 43, 78, 11, 40, 42, 62, 77])

In [157]:
a[2]

array([61, 68, 25, 58, 49, 23, 86, 77, 49, 60])

In [159]:
a[0][3]

94

In [171]:
# For multidimensional arrays:

# array[rows_slice, columns_slice]
a

array([[14, 65, 50, 94, 56, 68, 71, 64, 47, 22],
       [60, 71, 18, 43, 78, 11, 40, 42, 62, 77],
       [61, 68, 25, 58, 49, 23, 86, 77, 49, 60],
       [26, 46, 51, 96, 66, 79, 17, 12, 33, 75],
       [92, 23, 57, 69, 67, 75, 72, 59, 73, 46],
       [54, 93, 73, 57, 52, 82, 96, 48, 68, 55],
       [79, 44, 82, 46, 10, 35, 98, 22, 77, 11],
       [62, 70, 58, 94, 52, 41, 56, 10, 32, 79],
       [98, 73, 96, 42, 62, 29, 68, 13, 32, 39],
       [76, 42, 50, 20, 74, 59, 76, 45, 99, 14]])

In [167]:
a[0, :]    # First row, all columns



array([14, 65, 50, 94, 56, 68, 71, 64, 47, 22])

In [169]:
a[:, 1]    # All rows, second column

array([65, 71, 68, 46, 23, 93, 44, 70, 73, 42])

In [177]:
a[1,:]

array([60, 71, 18, 43, 78, 11, 40, 42, 62, 77])

In [181]:
a[:5,:4]

array([[14, 65, 50, 94],
       [60, 71, 18, 43],
       [61, 68, 25, 58],
       [26, 46, 51, 96],
       [92, 23, 57, 69]])

In [183]:
a[:8, :7]

array([[14, 65, 50, 94, 56, 68, 71],
       [60, 71, 18, 43, 78, 11, 40],
       [61, 68, 25, 58, 49, 23, 86],
       [26, 46, 51, 96, 66, 79, 17],
       [92, 23, 57, 69, 67, 75, 72],
       [54, 93, 73, 57, 52, 82, 96],
       [79, 44, 82, 46, 10, 35, 98],
       [62, 70, 58, 94, 52, 41, 56]])

In [189]:
a[0:2,2:4]

array([[50, 94],
       [18, 43]])

In [3]:
import numpy as np

In [7]:
np.random.randint(1,10)

7

In [11]:
np.random.randint(50)

46

In [13]:
np.random.randint(1,100,10)

array([76, 68, 23, 66, 35, 83, 50, 86, 82, 94])

In [15]:
np.random.randint(10,100,(10,10))

array([[74, 83, 38, 17, 30, 44, 32, 76, 36, 20],
       [80, 33, 65, 45, 85, 37, 39, 30, 63, 73],
       [61, 41, 52, 98, 46, 71, 36, 77, 53, 52],
       [71, 17, 41, 81, 10, 42, 38, 75, 86, 26],
       [41, 70, 22, 61, 80, 35, 88, 54, 43, 44],
       [59, 73, 87, 73, 32, 81, 46, 31, 94, 41],
       [38, 70, 33, 31, 37, 57, 21, 80, 52, 19],
       [69, 30, 99, 84, 47, 62, 63, 42, 78, 47],
       [99, 57, 72, 25, 12, 23, 15, 87, 74, 48],
       [41, 75, 68, 35, 59, 68, 16, 30, 91, 46]])

In [17]:
np.random.rand(10)

array([0.30315942, 0.77191562, 0.80912617, 0.45660182, 0.06791616,
       0.23183002, 0.43101623, 0.15159558, 0.09866162, 0.65992915])

In [19]:
np.random.randn(4,3)

array([[-0.34502363, -1.29682131,  2.07616474],
       [-0.85491046, -1.6578625 ,  0.00967536],
       [-0.47807267, -0.18810609,  0.67823542],
       [-0.4940709 , -0.57831708,  0.32306157]])

In [27]:
a= np.random.randint(11,100,(8,8))
a

array([[31, 31, 47, 87, 22, 48, 88, 57],
       [45, 77, 88, 78, 98, 48, 41, 63],
       [14, 33, 87, 35, 52, 11, 39, 99],
       [12, 12, 38, 19, 47, 25, 14, 48],
       [73, 96, 31, 26, 93, 38, 14, 64],
       [75, 72, 72, 23, 44, 87, 91, 73],
       [30, 71, 21, 71, 42, 25, 50, 86],
       [66, 85, 78, 60, 39, 48, 38, 84]])

In [29]:
a>50

array([[False, False, False,  True, False, False,  True,  True],
       [False,  True,  True,  True,  True, False, False,  True],
       [False, False,  True, False,  True, False, False,  True],
       [False, False, False, False, False, False, False, False],
       [ True,  True, False, False,  True, False, False,  True],
       [ True,  True,  True, False, False,  True,  True,  True],
       [False,  True, False,  True, False, False, False,  True],
       [ True,  True,  True,  True, False, False, False,  True]])

In [31]:
a[a>50] #boolean Masking

array([87, 88, 57, 77, 88, 78, 98, 63, 87, 52, 99, 73, 96, 93, 64, 75, 72,
       72, 87, 91, 73, 71, 71, 86, 66, 85, 78, 60, 84])

In [33]:
a[a<50] 

array([31, 31, 47, 22, 48, 45, 48, 41, 14, 33, 35, 11, 39, 12, 12, 38, 19,
       47, 25, 14, 48, 31, 26, 38, 14, 23, 44, 30, 21, 42, 25, 39, 48, 38])

In [35]:
a[a==50] 

array([50])

In [39]:
b = a[a<40]
print(b)
b[b>20]

[31 31 22 14 33 35 11 39 12 12 38 19 25 14 31 26 38 14 23 30 21 25 39 38]


array([31, 31, 22, 33, 35, 39, 38, 25, 31, 26, 38, 23, 30, 21, 25, 39, 38])

In [45]:
#SLICING
a = np.random.randint(10,100,(10,10))
a

array([[51, 90, 75, 71, 94, 24, 91, 33, 67, 87],
       [15, 47, 35, 87, 60, 37, 43, 67, 54, 51],
       [36, 63, 64, 51, 27, 26, 36, 68, 38, 41],
       [81, 12, 60, 42, 56, 65, 72, 27, 12, 26],
       [93, 22, 85, 95, 76, 75, 80, 69, 65, 99],
       [57, 15, 11, 72, 33, 48, 95, 38, 99, 69],
       [90, 11, 18, 74, 44, 33, 80, 78, 11, 26],
       [33, 18, 71, 72, 97, 12, 94, 28, 82, 18],
       [16, 20, 72, 69, 43, 31, 88, 62, 95, 71],
       [52, 57, 33, 31, 36, 75, 57, 83, 23, 14]])

In [43]:
a[0]

array([38, 41, 83, 82, 36, 57, 19, 26, 91, 11])

In [47]:
a[1]

array([15, 47, 35, 87, 60, 37, 43, 67, 54, 51])

In [49]:
a

array([[51, 90, 75, 71, 94, 24, 91, 33, 67, 87],
       [15, 47, 35, 87, 60, 37, 43, 67, 54, 51],
       [36, 63, 64, 51, 27, 26, 36, 68, 38, 41],
       [81, 12, 60, 42, 56, 65, 72, 27, 12, 26],
       [93, 22, 85, 95, 76, 75, 80, 69, 65, 99],
       [57, 15, 11, 72, 33, 48, 95, 38, 99, 69],
       [90, 11, 18, 74, 44, 33, 80, 78, 11, 26],
       [33, 18, 71, 72, 97, 12, 94, 28, 82, 18],
       [16, 20, 72, 69, 43, 31, 88, 62, 95, 71],
       [52, 57, 33, 31, 36, 75, 57, 83, 23, 14]])

In [51]:
a[6]

array([90, 11, 18, 74, 44, 33, 80, 78, 11, 26])

In [53]:
a[6][3]

74

In [55]:
a

array([[51, 90, 75, 71, 94, 24, 91, 33, 67, 87],
       [15, 47, 35, 87, 60, 37, 43, 67, 54, 51],
       [36, 63, 64, 51, 27, 26, 36, 68, 38, 41],
       [81, 12, 60, 42, 56, 65, 72, 27, 12, 26],
       [93, 22, 85, 95, 76, 75, 80, 69, 65, 99],
       [57, 15, 11, 72, 33, 48, 95, 38, 99, 69],
       [90, 11, 18, 74, 44, 33, 80, 78, 11, 26],
       [33, 18, 71, 72, 97, 12, 94, 28, 82, 18],
       [16, 20, 72, 69, 43, 31, 88, 62, 95, 71],
       [52, 57, 33, 31, 36, 75, 57, 83, 23, 14]])

In [59]:
a[0,:]

array([51, 90, 75, 71, 94, 24, 91, 33, 67, 87])